### PR TITLE
Feat/question component

### LINKED ISSUE #9: [FEAT] Implement Question Functionality
## Summary

Set up the questions and question bank for the Interview Page, enabling users to view and answer interview questions during an interview session.

## Motivation

The question bank is essential for the Interview Page functionality, allowing users to access a range of interview questions. This feature will facilitate a structured interview process and ensure that users have a diverse set of questions to answer.

### PR DESCRIPTION
**Pull request by tyin363**
## Context

This change is implemented to enable users to view and answer interview questions during their interview sessions. The question bank is now integrated with the Interview Page, allowing a range of questions to be accessed, which enhances the structured interview process.

Closes #9 

## What Changed?

- Added a Questions component
- Implemented functionality to display questions based on the selected question type.
- Ensured the question component is correctly rendered and updated according to the selected type.

## How To Review

1. Verify that the question bank is correctly populated with diverse interview questions.
2. Check that the Interview Page displays questions based on the selected question type.
3. Ensure that the question component renders correctly and updates as expected when switching between question types.
## Testing

- Verified that changing between question types updates the questions shown.
- Checked that the question component is rendered and functioning as intended.
## Risks

N/A 
## Notes
N/A

### CODE REVIEW

**Comment by today0-o** [comment]
Excellent work on the initial set up of the interview questions! It perfectly shows in the InterviewPractice page, and depending on the question type that we choose in the InterviewSettings page, the questions change as intended. The questions are also being randomised when it is displayed, which I think is a great implementation. Overall achieves our goal to have a 'question bank' for access.

However, there were some improvements I wanted to suggest.

### **Improvements**

- [ ] Populate the number of questions in both behavioural and technical question bank

### **Possible Suggestions**

- Have the questions show on the left side of the page with proper layout, following High-Fidelity design of the Interview practice page
- When an answer is submitted by the user, change the question to another question in the question bank

Let me know what you think about the suggestions that I have made! - remember that the suggestions are not necessarily to be done in this pull request. They can be future improvements to consider :).

**Comment by tyin363** [comment]
In response to your suggested improvements, I have added more questions to both question banks.

Regarding the possible changes, I believe the layout issue will be addressed in #26. The suggestion to "change the question to another question in the question bank when an answer is submitted by the user" will be addressed later when we integrate the Interview Settings with the Interview Page.

Let me know if you need any further changes.

**Comment by tyin363** [comment]
Great job on the implementation! The fix for recording length discrepancies is well-executed and effectively addresses the issue where the displayed length was slightly shorter than the actual video length. The 100ms timeout adjustment ensures accurate recording times, and your testing confirms that the displayed lengths are consistent with various timeout durations.

Possible Suggestions
- Integrate Interview Settings Time: Consider integrating the time set in the InterviewSettings page with the video's actual recording time. This could ensure that the video length matches the expected duration more precisely and provide a more seamless user experience.

Overall, everything looks good and ready to merge. The suggested integration is just a potential enhancement for future consideration. Keep up the excellent work!

**Comment by today0-o** [comment]
Looks great to me now! Thank you for the additional commits :). I will now merge the branch

**Pull request merged**
