### PR TITLE
Feat/initial SummaryPage setup

### LINKED ISSUE #19: [FEAT] Initial Summary Page implementation
A Summary page for after you finish all the interview recordings and questions for the current session. Displays information about user's most recent interview practice session

## Summary

- Summary page will have a summary of each questions you answered, and some basic statistics such as the duration of the answer
- Will also have a summary of the all the interview practice sessions you've had, and information such as average duration.

## Motivation

- By having a summary page, users are able to see a more general overview of their full interview session.
- Encourages users to continue using application, by shwoing progress
- Sets up a foundation for more detailed feebdack and analytics in future releases

## Detailed Description

- Recent Interview Practice section includes: Date of most recent practice session, questions asked, duration of session
- Practice Statistics section: Total number of practice sessions, average duration of sessions, and date of most recent practice.
- Motivational message, and a button to start new practice session
## Possible Alternatives

N/A
## Additional Context

N/A
## Implementation

- After creating a SummaryPage.js component, could use Card components to separate the sections.
- Needs to update Routing to include this new Summary Page.
- Interview statistics will have mock data for initial development and testing.

### PR DESCRIPTION
**Pull request by syoo881**
## Context

Setting up the Summary page for when user finishes their interviews. Will display basic information.

## What Changed?

- Created a new file called SummaryPage.js that contains the summary of interview, and redirects to either home page or back to the interview
- Changed InterviewPractice.js file to link to the SummaryPage by adding a "Next" button
- Changed how InterviewPractice.js stores the time remaining for each interview video, by setting it as a const, and subsequently sending that state over to the SummaryPage once you route to it

## How To Review

- Check the SummaryPage.js file to ensure all the core functionalities are there - not all of them have been fully implemented due to limitations of the other pages at this stage
- Ensure that InterviewPractice.js hasn't been broken, and the features from previous builds still work.

## Testing

- Tested using console.log() whether the state was being sent over from the InterviewPractice.js page to the SummaryPage.js - works as intended.

## Risks

- Make sure that InterviewPractice.jsn page hasn't been broken, and the core logic that was intended still remains.
## Notes

Closes #19

### CODE REVIEW

**Review by RusiruD — COMMENTED** [review]
Excellent work on the initial set up of the interview summary page, it displays accurate information gathered from the recorded interview and displays it neatly. There seems to be no bugs caused by this page in the interview practice page or the summary page itself.
 
However, I do want to suggest some changes, that I think will allow the PR to become ready for merging:

### Improvements
- [ ] The Go Home button is the colour grey which may make users think it is disabled, I suggest changing the colour of this button away from grey.


### Possible Suggestions
- Add some text in the interview practice page that tells the user they can see a summary by clicking the next button when it appears, or modify the next buttons text to be more self descriptive.
- Allow the page to have memory of more than 1 previous practice interview.
- Include information on the difficulty of the question answered
- Include feedback on the length of the recorded answer i.e shorter than expected.

These don't need to be implemented in this pull request, but could be feature improvements down the line.

**Comment by syoo881** [comment]
I've just added a feature to change the color from grey to a shade of light blue - would be nice if you double check if the change fixes the issue @RusiruD

**Review by RusiruD — APPROVED** [review]
Changed button colours looks good and fits with the design theme, great work.

**Comment by RusiruD** [comment]
Great work on this page, my suggestions from before the change still apply but they can be implmented later. Great work fixing the Go Home button it looks much better.

**Pull request merged**
